### ISSUE TITLE
Escrever tweets com html ao invés de imagens

### ISSUE THREAD

**Issue by osouzajefferson** [LukeberryPi/posso-perguntar#1]
as imagens ficam borradas em algumas resoluções, clonar o css do twitter resolveria para esse caso

![do](https://user-images.githubusercontent.com/2744100/205516563-44d38982-c287-4b98-9955-c4f235945b58.png)

**Comment by LukeberryPi** [comment]
Valeu pela sugestão! Vou puxar essa demanda, curti a ideia
