### ISSUE TITLE
Link para tweet está "atrás" da div com class="tweet"

### ISSUE THREAD

**Issue by osouzajefferson** [LukeberryPi/posso-perguntar#6]
Nas imagens dos tweets, não é possível clicar pois o link está escondido atrás de uma div com class tweet(segunda imagem). A solução simples seria colocar o link clicável nessa mesma div ou colocar a tag <a> por fora dela. 

<img width="488" alt="image" src="https://github.com/LukeberryPi/posso-perguntar/assets/2744100/0f0dacff-f869-4ffd-90f0-36550bccd48f">

<img width="673" alt="image" src="https://github.com/LukeberryPi/posso-perguntar/assets/2744100/4435219b-0717-4d66-b777-b8881dd0d709">

**Comment by LukeberryPi** [comment]
consertado
